from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parent

for folder in ['pages', 'core', 'services', 'ui', 'data', 'assets', 'outputs', '.streamlit']:
    (ROOT / folder).mkdir(exist_ok=True)

for package in ['pages', 'core', 'services', 'ui']:
    (ROOT / package / '__init__.py').touch(exist_ok=True)

app_path = ROOT / 'app.py'
backup_path = ROOT / 'backup_app_bai12.py'
if app_path.exists() and not backup_path.exists():
    shutil.copy2(app_path, backup_path)

(ROOT / '.streamlit' / 'config.toml').write_text('[theme]\nbase = "light"\nprimaryColor = "#D989A5"\nbackgroundColor = "#FFF9FB"\nsecondaryBackgroundColor = "#FCECF2"\ntextColor = "#493A43"\nfont = "sans serif"\n\n[server]\nheadless = true\n\n[browser]\ngatherUsageStats = false\n', encoding='utf-8')
(ROOT / 'ui' / 'theme.py').write_text('import streamlit as st\n\nPASTEL_COLORS = [\n    "#D989A5",\n    "#F4B8C8",\n    "#CDB8E5",\n    "#A8D5D1",\n    "#F2D7A7",\n    "#A9C9E8",\n]\n\n\ndef apply_theme() -> None:\n    st.markdown(\n        """\n        <style>\n        .stApp {\n            background: linear-gradient(\n                135deg,\n                #fff9fb 0%,\n                #fffdfd 48%,\n                #f9f5fc 100%\n            );\n        }\n\n        [data-testid="stSidebar"] {\n            background: linear-gradient(\n                180deg,\n                #fcecf2 0%,\n                #faf5fb 100%\n            );\n            border-right: 1px solid #f1d6e1;\n        }\n\n        .page-hero {\n            padding: 24px 28px;\n            border-radius: 22px;\n            background: linear-gradient(\n                120deg,\n                #f5c5d5 0%,\n                #eadcf5 55%,\n                #d9edf0 100%\n            );\n            border: 1px solid rgba(217, 137, 165, 0.28);\n            box-shadow: 0 10px 30px rgba(105, 73, 91, 0.10);\n            margin-bottom: 18px;\n        }\n\n        .page-hero h1 {\n            color: #503743;\n            margin: 0;\n            font-size: 2rem;\n        }\n\n        .page-hero p {\n            color: #705865;\n            margin: 8px 0 0;\n        }\n\n        [data-testid="stMetric"] {\n            background: rgba(255, 255, 255, 0.85);\n            border: 1px solid #f0d5df;\n            border-radius: 18px;\n            padding: 15px;\n            box-shadow: 0 6px 22px rgba(105, 73, 91, 0.07);\n        }\n\n        div.stButton > button {\n            border-radius: 12px;\n            border: 1px solid #d989a5;\n            background: #d989a5;\n            color: white;\n            font-weight: 600;\n            min-height: 42px;\n        }\n\n        div.stButton > button:hover {\n            background: #c87492;\n            border-color: #c87492;\n            color: white;\n        }\n\n        [data-testid="stDataFrame"] {\n            border: 1px solid #f0d5df;\n            border-radius: 14px;\n            overflow: hidden;\n        }\n        </style>\n        """,\n        unsafe_allow_html=True,\n    )\n\n\ndef page_header(title: str, subtitle: str) -> None:\n    st.markdown(\n        f"""\n        <div class="page-hero">\n            <h1>{title}</h1>\n            <p>{subtitle}</p>\n        </div>\n        """,\n        unsafe_allow_html=True,\n    )\n', encoding='utf-8')
(ROOT / 'app.py').write_text('import streamlit as st\n\nfrom ui.theme import apply_theme\n\nst.set_page_config(\n    page_title="VN AIDEOM-VN",\n    page_icon="🌸",\n    layout="wide",\n    initial_sidebar_state="expanded",\n)\n\napply_theme()\n\npages = {\n    "VN AIDEOM-VN": [\n        st.Page(\n            "pages/home.py",\n            title="Trang chủ",\n            icon="🏠",\n            default=True,\n        ),\n    ],\n    "Cấp độ dễ": [\n        st.Page("pages/bai01.py", title="Bài 1 — Cobb-Douglas + AI", icon="🌱"),\n        st.Page("pages/bai02.py", title="Bài 2 — LP ngân sách số", icon="💰"),\n        st.Page("pages/bai03.py", title="Bài 3 — Priority 10 ngành", icon="📊"),\n    ],\n    "Cấp độ trung bình": [\n        st.Page("pages/bai04.py", title="Bài 4 — LP ngành-vùng", icon="🗺️"),\n        st.Page("pages/bai05.py", title="Bài 5 — MIP 15 dự án", icon="🎯"),\n        st.Page("pages/bai06.py", title="Bài 6 — TOPSIS 6 vùng", icon="🏆"),\n    ],\n    "Cấp độ nâng cao": [\n        st.Page("pages/bai07.py", title="Bài 7 — NSGA-II Pareto", icon="🌐"),\n        st.Page("pages/bai08.py", title="Bài 8 — Tối ưu động", icon="⌛"),\n        st.Page("pages/bai09.py", title="Bài 9 — Lao động & AI", icon="👥"),\n    ],\n    "Cấp độ chuyên sâu": [\n        st.Page("pages/bai10.py", title="Bài 10 — Stochastic SP", icon="🎲"),\n        st.Page("pages/bai11.py", title="Bài 11 — Q-learning RL", icon="🤖"),\n        st.Page("pages/bai12.py", title="Bài 12 — AIDEOM tích hợp", icon="🇻🇳"),\n    ],\n}\n\nnavigation = st.navigation(\n    pages,\n    position="sidebar",\n)\n\nnavigation.run()\n', encoding='utf-8')
(ROOT / 'pages' / 'home.py').write_text('import streamlit as st\n\nfrom ui.theme import page_header\n\npage_header(\n    "VN AIDEOM-VN",\n    "AI-Driven Decision Optimization Model for Vietnam",\n)\n\nst.markdown(\n    """\n    Hệ thống web tích hợp **12 bài toán mô hình ra quyết định**,\n    hỗ trợ phân tích chính sách phát triển kinh tế Việt Nam\n    trong kỷ nguyên trí tuệ nhân tạo.\n    """\n)\n\ncol1, col2, col3, col4 = st.columns(4)\n\ncol1.metric("Bài toán", "12")\ncol2.metric("Nhóm mô hình", "4")\ncol3.metric("Kịch bản Bài 12", "5")\ncol4.metric("Tác nhân AI", "12")\n\nst.divider()\nst.subheader("📚 12 bài toán theo 4 cấp độ")\n\nwith st.expander("🟢 Cấp độ dễ — Làm quen mô hình", expanded=True):\n    st.markdown(\n        """\n        - **Bài 1:** Cobb-Douglas mở rộng và dự báo GDP.\n        - **Bài 2:** LP phân bổ ngân sách số.\n        - **Bài 3:** Chỉ số ưu tiên 10 ngành.\n        """\n    )\n\nwith st.expander("🟡 Cấp độ trung bình — Tối ưu cổ điển"):\n    st.markdown(\n        """\n        - **Bài 4:** Phân bổ vùng và công bằng số.\n        - **Bài 5:** Lựa chọn danh mục 15 dự án.\n        - **Bài 6:** TOPSIS, Entropy và AHP.\n        """\n    )\n\nwith st.expander("🟠 Cấp độ nâng cao — Đa mục tiêu và động"):\n    st.markdown(\n        """\n        - **Bài 7:** NSGA-II và đường biên Pareto.\n        - **Bài 8:** Tối ưu liên thời gian 2026-2035.\n        - **Bài 9:** Lao động và trí tuệ nhân tạo.\n        """\n    )\n\nwith st.expander("🔴 Cấp độ chuyên sâu — Bất định và AI"):\n    st.markdown(\n        """\n        - **Bài 10:** Stochastic Programming.\n        - **Bài 11:** Q-learning và DQN.\n        - **Bài 12:** Hệ thống AIDEOM-VN tích hợp.\n        """\n    )\n\nst.divider()\nst.subheader("🧭 Quy trình sử dụng")\nst.markdown(\n    """\n    1. Chọn bài toán ở thanh menu bên trái.\n    2. Điều chỉnh tham số đầu vào.\n    3. Bấm **Chạy mô hình**.\n    4. Xem bảng, KPI và biểu đồ.\n    5. Bấm **Phân tích kết quả bằng AI**.\n    6. Tải kết quả để đưa vào báo cáo.\n    """\n)\n\nst.caption(\n    "Đây là khung giao diện. Thuật toán từng bài sẽ được tích hợp ở các bước tiếp theo."\n)\n', encoding='utf-8')

PAGE_INFO = {1: ('Bài 1 — Cobb-Douglas + AI', 'Tính TFP, phân rã tăng trưởng và dự báo GDP.', 'Cobb-Douglas mở rộng'), 2: ('Bài 2 — LP phân bổ ngân sách số', 'Tối ưu bốn hạng mục và shadow price.', 'Linear Programming'), 3: ('Bài 3 — Priority 10 ngành', 'Chuẩn hóa, xếp hạng và độ nhạy trọng số.', 'Weighted Scoring'), 4: ('Bài 4 — LP ngành-vùng', 'Phân bổ vùng × hạng mục và công bằng.', 'Linear Programming'), 5: ('Bài 5 — MIP lựa chọn 15 dự án', 'Lựa chọn danh mục dự án tối ưu.', 'Mixed Integer Programming'), 6: ('Bài 6 — TOPSIS 6 vùng', 'TOPSIS, Entropy và AHP.', 'MCDM'), 7: ('Bài 7 — NSGA-II Pareto', 'Tối ưu đa mục tiêu.', 'NSGA-II'), 8: ('Bài 8 — Tối ưu động 2026-2035', 'Phân bổ đầu tư liên thời gian.', 'Dynamic Optimization'), 9: ('Bài 9 — Lao động và AI', 'Việc làm mới, mất việc và đào tạo lại.', 'Labor Market Optimization'), 10: ('Bài 10 — Stochastic Programming', 'EV, EEV, VSS, EVPI và robust regret.', 'Two-stage Stochastic Programming'), 11: ('Bài 11 — Q-learning và DQN', 'Học chính sách phân bổ thích nghi.', 'Reinforcement Learning'), 12: ('Bài 12 — AIDEOM-VN tích hợp', 'Dashboard M1-M6 và năm kịch bản.', 'Integrated Decision-Support System')}
PAGE_TEMPLATE = 'import streamlit as st\n\nfrom ui.theme import page_header\n\npage_header(\n    {title!r},\n    {subtitle!r},\n)\n\ntab1, tab2, tab3, tab4 = st.tabs(\n    [\n        "📘 Mô hình",\n        "⚙️ Tham số",\n        "📊 Kết quả",\n        "✨ Phân tích AI",\n    ]\n)\n\nwith tab1:\n    st.subheader("Mô hình sử dụng")\n    st.info({model!r})\n    st.write(\n        "Trang khung đã hoạt động. Bước tiếp theo là kết nối "\n        "thuật toán Bài {number} với giao diện."\n    )\n\nwith tab2:\n    st.subheader("Tham số đầu vào")\n    st.number_input(\n        "Tham số minh họa",\n        min_value=0.0,\n        value=100.0,\n        key="parameter_{number}",\n    )\n    st.button(\n        "Chạy mô hình",\n        key="run_{number}",\n        use_container_width=True,\n    )\n\nwith tab3:\n    st.subheader("Kết quả mô hình")\n    st.warning("Chưa kết nối thuật toán Bài {number}.")\n\nwith tab4:\n    st.subheader("Tác nhân phân tích kết quả")\n    st.button(\n        "Phân tích kết quả bằng AI",\n        key="ai_{number}",\n        use_container_width=True,\n    )\n    st.caption(\n        "Gemini sẽ được kết nối sau khi mô hình trả về kết quả."\n    )\n'

for number, (title, subtitle, model) in PAGE_INFO.items():
    content = PAGE_TEMPLATE.format(
        title=title,
        subtitle=subtitle,
        model=model,
        number=number,
    )
    (ROOT / 'pages' / f'bai{number:02d}.py').write_text(content, encoding='utf-8')

print('=' * 70)
print('ĐÃ TẠO XONG KHUNG WEBSITE TRANG CHỦ + 12 MENU')
print('=' * 70)
print(f'Thư mục dự án: {ROOT}')
print('App Bài 12 cũ đã sao lưu tại: backup_app_bai12.py')
print('Chạy web bằng: python -m streamlit run app.py')
